sudo: required
language: python
python:
  - "3.5"
addons:
  chrome: stable
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/.
  - sleep 3
install:
  - pip install -r requirements.txt
script:
  - python -m unittest
notifications:
  email:
    - pf-developers@ebi.ac.uk