sudo: required
language: python
python:
  - "3.5"
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
before_install:
  - wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/.
  - sleep 3
install:
  - pip install -r requirements.txt
script:
  - python -m unittest
notifications:
  email:
    - gsalazar@ebi.ac.uk
    - maq@ebi.ac.uk
